### ISSUE TITLE
Invalid use of DisableThreadLibraryCalls (...)

### ISSUE THREAD

**Issue by Kaldaien** [crosire/reshade#20]
It has come to my attention that the default build configuration for ReShade statically links to the Visual C++ runtime and then turns around and makes this dangerous call to `DisableThreadLibraryCalls (...)`.

The C++ runtime needs thread attach / detach notifications for its memory allocator to function correctly. Likewise, OpenGL uses thread-local-storage for each render context. If you are hooking OpenGL, you should make sure thread local storage is working sanely :)

To this end, I would suggest changing ReShade's build config to:

 1. NOT statically link to the C++ runtime
 2. Stop calling `DisableThreadLibraryCalls (...)`

**Comment by crosire** [comment]
ReShade was previously linked dynamically against the CRT, but that was changed since users repeatedly forgot to install the redistributable package as explained on the download page and complained about the application not working. Didn't realize the `DisableThreadLibraryCalls` call was still in, thanks for pointing that out!
